services:
  web:
    build: .
    ports:
      - ${API_PORT}:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./src:/app
    networks:
      - lexie
    depends_on:
      - redis

  redis:
    image: redis:7.0.2-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test: "redis-cli PING"
      interval: 2s
      retries: 10
    networks:
      - lexie

networks:
  lexie: